# Generated by Django 3.2.5 on 2022-01-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='resume',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='image'),
        ),
    ]
